require 'colorize'
require 'highline/import'
require 'inquirer'
require 'active_support/core_ext/object/blank'
require 'active_support/core_ext/string/inflections'

require 'English'
require 'fileutils'
require 'ostruct'
require 'open3'
require 'optparse'
require 'pathname'
require 'pty'
require 'securerandom'
require 'shellwords'

require 'pineapples/version'
require 'pineapples/error'
require 'pineapples/app_generator'
require 'pineapples/parser'
